const wordData = [
  { word: "职员", meaning: "staff member; employee", example: "他是公司的职员。" },
  { word: "研究所", meaning: "graduate school", example: "她打算申请研究所。" },
  { word: "研究", meaning: "research; to research", example: "他在研究这个问题。" },
  { word: "课程", meaning: "course; curriculum", example: "这门课程很有意思。" },
  { word: "通知", meaning: "to notify; notification", example: "老师已经通知学生了。" },
  { word: "广告", meaning: "advertisement", example: "这个广告很有名。" },
  { word: "设计", meaning: "to design; design", example: "她负责设计海报。" },
  { word: "想法", meaning: "idea; thought", example: "我有一个新的想法。" },
  { word: "听力", meaning: "listening ability", example: "他的中文听力很好。" },
  { word: "会话", meaning: "conversation", example: "我们练习日常会话。" },
  { word: "所", meaning: "place; institute; classifier", example: "这是一所大学。" },
  { word: "外语", meaning: "foreign language", example: "他会三种外语。" },
  { word: "学院", meaning: "college; institute", example: "她在外国语学院读书。" },
  { word: "哲学", meaning: "philosophy", example: "他对哲学很感兴趣。" },
  { word: "专业", meaning: "major; specialty; professional", example: "这是我的专业。" },
  { word: "困难", meaning: "difficulty; difficult", example: "这个问题很困难。" },
  { word: "职业", meaning: "occupation; profession", example: "你将来想做什么职业？" },
  { word: "起", meaning: "to begin", example: "会议三点起开始。" },
  { word: "助理", meaning: "assistant", example: "她是教授的助理。" },
  { word: "向", meaning: "towards; to", example: "他向老师请教问题。" },
  { word: "贸易", meaning: "trade", example: "国际贸易很重要。" },
  { word: "保险", meaning: "insurance", example: "他买了健康保险。" },
  { word: "经理", meaning: "manager", example: "经理正在开会。" },
  { word: "管理", meaning: "to manage; management", example: "他负责公司管理。" },
  { word: "员工", meaning: "employee", example: "公司有很多员工。" },
  { word: "开会", meaning: "to have a meeting", example: "我们下午要开会。" },
  { word: "加班", meaning: "to work overtime", example: "他昨天加班到很晚。" },
  { word: "难怪", meaning: "no wonder", example: "难怪他这么累。" },
  { word: "退休", meaning: "to retire", example: "他明年就退休了。" }
];
